name: run_pipeline
on:
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * MON-FRI"
jobs:
  run_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup_env
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.9"
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run job
        env:
            AZUREDATALAKE: ${{ secrets.AZUREDATALAKE }}
        run: python etl.py 
